apiVersion: v1
kind: Service
metadata:
  name: nodejs-master
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nodejs-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: consensusclubs/node-eos-example:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
