apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
spec:
  restartPolicy: Never
  containers:
  - name: nodejs-container
    image: consensusclubs/node-eos-example:v1.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "node /app/app.js" ]
